In [1]:
import tensorflow as tf

In [2]:
a=tf.constant([1,2,3,4])
b=tf.constant([4,5,6,7])

In [3]:
res=tf.multiply(a,b)

In [4]:
sess=tf.Session()

In [5]:
print(sess.run(res))

[ 4 10 18 28]


In [6]:
sess.close()

In [7]:
with tf.Session() as sess1:
    out=sess1.run(res)
    print(out)

[ 4 10 18 28]


In [8]:
scalar=tf.constant([20])
vector=tf.constant([1,2,3])
matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor=tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]],[[2,3,1],[5,6,4],[8,9,7]]])
with tf.Session() as session:
    result=session.run(scalar)
    print ("scalar :") 
    print (result)
    result=session.run(vector)
    print("vector : ")
    print (result)
    result=session.run(matrix)
    print("matrix : " )
    print (result)
    result=session.run(tensor)
    print("tensor : ")
    print (result)

scalar :
[20]
vector : 
[1 2 3]
matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor : 
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]

 [[2 3 1]
  [5 6 4]
  [8 9 7]]]


In [9]:
matrix1=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix2=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

op1=tf.add(matrix1,matrix2)
op2=matrix1+matrix2

In [10]:
op1

<tf.Tensor 'Add:0' shape=(3, 3) dtype=int32>

In [11]:
with tf.Session() as sess2:
    result=sess2.run(op1)
    print ("op1 : ")
    print(result)
    result=sess2.run(op2)
    print ("op2 : ")
    print(result)

op1 : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
op2 : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
state=tf.Variable(0)

In [13]:
one=tf.constant(1)
new=tf.add(state,one)
update=tf.assign(state,new)

In [14]:
#init_op=tf.initialize_all_variables()
init_op1=tf.global_variables_initializer()

In [15]:
with tf.Session() as sess3:
    sess3.run(init_op1)
    print(sess3.run(state))
    for _ in range(3):
        sess3.run(update)
        print(sess3.run(state))

0
1
2
3


In [16]:
a=tf.placeholder(tf.float32)

In [17]:
b=a*2

In [18]:
with tf.Session() as sess4:
    result=sess4.run(b,feed_dict={a:4})
    print (result)

8.0


# one dimension tensor

In [21]:
import numpy as np
t_1d=np.array([1,2,3,4])

In [23]:
print(t_1d)

[1 2 3 4]


In [25]:
print(t_1d.ndim)

1


In [26]:
print(t_1d.shape)

(4,)


In [27]:
print(t_1d.dtype)

int32


In [30]:
one=tf.convert_to_tensor(t_1d,dtype=tf.int64)

In [31]:
one

<tf.Tensor 'Const_10:0' shape=(4,) dtype=int64>

In [34]:
with tf.Session() as sess5:
    print (sess5.run(one))
    print (sess5.run(one[0]))

[1 2 3 4]
1


In [35]:
t_2d=np.array(np.arange(16).reshape(4,4),dtype='int32')

In [36]:
t_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
two=tf.convert_to_tensor(t_2d)

In [39]:
with tf.Session() as sess6:
    print(sess6.run(two))
    print(sess6.run(two[0]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]


In [41]:
x=np.array(np.arange(16).reshape(4,4),dtype='int32')
y=np.array(np.arange(16,32).reshape(4,4),dtype='int32')

In [44]:
x1=tf.convert_to_tensor(x)
y1=tf.convert_to_tensor(y)

In [46]:
with tf.Session() as sess7:
    out1=tf.add(x1,y1)
    out2=tf.multiply(x1,y1)
    out3=tf.matmul(x1,y1)
    print('add')
    print(sess7.run(out1))
    print('multi')
    print(sess7.run(out2))
    print('matrix_mult')
    print(sess7.run(out3))

add
[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
multi
[[  0  17  36  57]
 [ 80 105 132 161]
 [192 225 260 297]
 [336 377 420 465]]
matrix_mult
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]
